AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  backoffice:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda/index.handler
      Runtime: nodejs12.x
      Description: 'BackOffice Lambda Index'
      MemorySize: 128
      Timeout: 20
      Role: 'arn:aws:iam::180677353921:role/CoredotLambdaSQSRDSCogSMRole'
      AutoPublishAlias: live
      VpcConfig:
        SecurityGroupIds:
          - sg-0e2bd8387180359c9
        SubnetIds:
          - subnet-0732d7b0216fbe2f7
          - subnet-078099e1972636375
          - subnet-08a164a0080a216c4
          - subnet-00c6531721f8d485a
      Environment:
        Variables:
          DB_NAME: shift
          DB_PORT: '3306'
          DB_USER: coredot
          DB_ENDPOINT: shift-dev-aurora-cluster.cluster-c89v5jzuome9.ap-northeast-2.rds.amazonaws.com
          DB_RO_ENDPOINT: shift-dev-aurora-cluster.cluster-ro-c89v5jzuome9.ap-northeast-2.rds.amazonaws.com
          DB_SM_ID : shift/product/aurora/coredot
          REGION: ap-northeast-2
          PLAN_ID : was7u8
          SM_ID : shift/product/kasinfo
          COGNITO_USER_POOL_ID : ap-northeast-2_vouGSpYU7
          PARAMETER_STORE_VALUE : 'dev_maintenance'